//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace InstrumentData
{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.frannuca.org/quantrisk/marketdata")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.frannuca.org/quantrisk/marketdata", IsNullable = false)]
    public partial class Marketdata
    {

        private System.DateTime referenceDateField;

        private MDseries[] dividendsField;

        private MDseries[] volalitiesField;

        private MDseries[] spotsField;

        private MDseries[] ratesField;

        private HestonVolatility[] stochasticVolatilitiesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime referenceDate
        {
            get
            {
                return this.referenceDateField;
            }
            set
            {
                this.referenceDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dividends")]
        public MDseries[] dividends
        {
            get
            {
                return this.dividendsField;
            }
            set
            {
                this.dividendsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("volalities")]
        public MDseries[] volalities
        {
            get
            {
                return this.volalitiesField;
            }
            set
            {
                this.volalitiesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("spots")]
        public MDseries[] spots
        {
            get
            {
                return this.spotsField;
            }
            set
            {
                this.spotsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rates")]
        public MDseries[] rates
        {
            get
            {
                return this.ratesField;
            }
            set
            {
                this.ratesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("stochasticVolatilities")]
        public HestonVolatility[] stochasticVolatilities
        {
            get
            {
                return this.stochasticVolatilitiesField;
            }
            set
            {
                this.stochasticVolatilitiesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.frannuca.org/quantrisk/marketdata")]
    public partial class MDseries : Identifier
    {

        private TimeUnits timeunitsField;

        private Point[] pointsField;

        /// <remarks/>
        public TimeUnits timeunits
        {
            get
            {
                return this.timeunitsField;
            }
            set
            {
                this.timeunitsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("points")]
        public Point[] points
        {
            get
            {
                return this.pointsField;
            }
            set
            {
                this.pointsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.frannuca.org/quantrisk/commons")]
    public enum TimeUnits
    {

        /// <remarks/>
        days,

        /// <remarks/>
        weeks,

        /// <remarks/>
        months,

        /// <remarks/>
        years,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.frannuca.org/quantrisk/commons")]
    public partial class Point
    {

        private double xField;

        private double yField;

        /// <remarks/>
        public double x
        {
            get
            {
                return this.xField;
            }
            set
            {
                this.xField = value;
            }
        }

        /// <remarks/>
        public double y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CorrelationMatrix
    {

        private double[] dataField;

        private string[] assetsField;

        private bool isRowMajorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data")]
        public double[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("assets")]
        public string[] assets
        {
            get
            {
                return this.assetsField;
            }
            set
            {
                this.assetsField = value;
            }
        }

        /// <remarks/>
        public bool isRowMajor
        {
            get
            {
                return this.isRowMajorField;
            }
            set
            {
                this.isRowMajorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.frannuca.org/quantrisk/commons")]
    public partial class Schedule
    {

        private Frequency frequencyField;

        private uint number_of_periodsField;

        /// <remarks/>
        public Frequency frequency
        {
            get
            {
                return this.frequencyField;
            }
            set
            {
                this.frequencyField = value;
            }
        }

        /// <remarks/>
        public uint number_of_periods
        {
            get
            {
                return this.number_of_periodsField;
            }
            set
            {
                this.number_of_periodsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.frannuca.org/quantrisk/commons")]
    public enum Frequency
    {

        /// <remarks/>
        Daily,

        /// <remarks/>
        Weekly,

        /// <remarks/>
        Monthly,

        /// <remarks/>
        Quarterly,

        /// <remarks/>
        Semiannual,

        /// <remarks/>
        Annual,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.frannuca.org/quantrisk/instrument")]
    public partial class CashFlow
    {

        private double nominalField;

        private Identifier rateIdField;

        private DayCountConvention daycountField;

        private DateAdjustment dateAdjustmentField;

        private Schedule scheduleField;

        /// <remarks/>
        public double Nominal
        {
            get
            {
                return this.nominalField;
            }
            set
            {
                this.nominalField = value;
            }
        }

        /// <remarks/>
        public Identifier rateId
        {
            get
            {
                return this.rateIdField;
            }
            set
            {
                this.rateIdField = value;
            }
        }

        /// <remarks/>
        public DayCountConvention daycount
        {
            get
            {
                return this.daycountField;
            }
            set
            {
                this.daycountField = value;
            }
        }

        /// <remarks/>
        public DateAdjustment dateAdjustment
        {
            get
            {
                return this.dateAdjustmentField;
            }
            set
            {
                this.dateAdjustmentField = value;
            }
        }

        /// <remarks/>
        public Schedule schedule
        {
            get
            {
                return this.scheduleField;
            }
            set
            {
                this.scheduleField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HestonVolatility))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MDseries))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Instrument))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TotalReturnSwap))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InterestRateSwap))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Forward))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OptionBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Currency))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.frannuca.org/quantrisk/commons")]
    public partial class Identifier
    {

        private double weightField;

        private string idField;

        private string nameField;

        public Identifier()
        {
            this.weightField = 1D;
        }

        /// <remarks/>
        public double weight
        {
            get
            {
                return this.weightField;
            }
            set
            {
                this.weightField = value;
            }
        }

        /// <remarks/>
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.frannuca.org/quantrisk/marketdata")]
    public partial class HestonVolatility : Identifier
    {

        private double thetaField;

        private double kappaField;

        private double voField;

        private double lambdaField;

        private double sigmaField;

        private double rhoField;

        private double gamma1Field;

        private double gamma2Field;

        /// <remarks/>
        public double theta
        {
            get
            {
                return this.thetaField;
            }
            set
            {
                this.thetaField = value;
            }
        }

        /// <remarks/>
        public double kappa
        {
            get
            {
                return this.kappaField;
            }
            set
            {
                this.kappaField = value;
            }
        }

        /// <remarks/>
        public double Vo
        {
            get
            {
                return this.voField;
            }
            set
            {
                this.voField = value;
            }
        }

        /// <remarks/>
        public double lambda
        {
            get
            {
                return this.lambdaField;
            }
            set
            {
                this.lambdaField = value;
            }
        }

        /// <remarks/>
        public double sigma
        {
            get
            {
                return this.sigmaField;
            }
            set
            {
                this.sigmaField = value;
            }
        }

        /// <remarks/>
        public double rho
        {
            get
            {
                return this.rhoField;
            }
            set
            {
                this.rhoField = value;
            }
        }

        /// <remarks/>
        public double gamma1
        {
            get
            {
                return this.gamma1Field;
            }
            set
            {
                this.gamma1Field = value;
            }
        }

        /// <remarks/>
        public double gamma2
        {
            get
            {
                return this.gamma2Field;
            }
            set
            {
                this.gamma2Field = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TotalReturnSwap))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InterestRateSwap))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Forward))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OptionBase))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.frannuca.org/quantrisk/instrument")]
    public partial class Instrument : Identifier
    {

        private System.DateTime expiryField;

        private System.DateTime startdateField;

        private System.DateTime settlementdateField;

        private Currency currencyField;

        private DayCountConvention daycountField;

        private DateAdjustment dateAdjustmentField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime expiry
        {
            get
            {
                return this.expiryField;
            }
            set
            {
                this.expiryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime startdate
        {
            get
            {
                return this.startdateField;
            }
            set
            {
                this.startdateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime settlementdate
        {
            get
            {
                return this.settlementdateField;
            }
            set
            {
                this.settlementdateField = value;
            }
        }

        /// <remarks/>
        public Currency currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }

        /// <remarks/>
        public DayCountConvention daycount
        {
            get
            {
                return this.daycountField;
            }
            set
            {
                this.daycountField = value;
            }
        }

        /// <remarks/>
        public DateAdjustment dateAdjustment
        {
            get
            {
                return this.dateAdjustmentField;
            }
            set
            {
                this.dateAdjustmentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.frannuca.org/quantrisk/commons")]
    public partial class Currency : Identifier
    {

        private string isocodeField;

        /// <remarks/>
        public string isocode
        {
            get
            {
                return this.isocodeField;
            }
            set
            {
                this.isocodeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.frannuca.org/quantrisk/commons")]
    public enum DayCountConvention
    {

        /// <remarks/>
        THIRTY_360,

        /// <remarks/>
        THIRTY_365,

        /// <remarks/>
        ACTUAL,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ACTUAL")]
        ACTUAL1,

        /// <remarks/>
        ACTUAL_ACTUAL,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.frannuca.org/quantrisk/commons")]
    public enum DateAdjustment
    {

        /// <remarks/>
        NoAdjustment,

        /// <remarks/>
        Previous,

        /// <remarks/>
        Following,

        /// <remarks/>
        ModifiedPrevious,

        /// <remarks/>
        ModifiedFollowing,

        /// <remarks/>
        EndOfMonth_NoAdj,

        /// <remarks/>
        EndOfMonth_Previous,

        /// <remarks/>
        EndOfMonth_Following,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.frannuca.org/quantrisk/instrument")]
    public partial class TotalReturnSwap : Instrument
    {

        private CashFlow leg_1Field;

        private Basket leg_2Field;

        /// <remarks/>
        public CashFlow leg_1
        {
            get
            {
                return this.leg_1Field;
            }
            set
            {
                this.leg_1Field = value;
            }
        }

        /// <remarks/>
        public Basket leg_2
        {
            get
            {
                return this.leg_2Field;
            }
            set
            {
                this.leg_2Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.frannuca.org/quantrisk/instrument")]
    public partial class Basket
    {

        private Identifier[] componentsField;

        private BasketAggregation basketAggregationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("components")]
        public Identifier[] components
        {
            get
            {
                return this.componentsField;
            }
            set
            {
                this.componentsField = value;
            }
        }

        /// <remarks/>
        public BasketAggregation basketAggregation
        {
            get
            {
                return this.basketAggregationField;
            }
            set
            {
                this.basketAggregationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.frannuca.org/quantrisk/commons")]
    public enum BasketAggregation
    {

        /// <remarks/>
        WORSTOF,

        /// <remarks/>
        BESTOF,

        /// <remarks/>
        AVERAGE,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.frannuca.org/quantrisk/instrument")]
    public partial class InterestRateSwap : Instrument
    {

        private CashFlow leg_1Field;

        private CashFlow leg_2Field;

        /// <remarks/>
        public CashFlow leg_1
        {
            get
            {
                return this.leg_1Field;
            }
            set
            {
                this.leg_1Field = value;
            }
        }

        /// <remarks/>
        public CashFlow leg_2
        {
            get
            {
                return this.leg_2Field;
            }
            set
            {
                this.leg_2Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.frannuca.org/quantrisk/instrument")]
    public partial class Forward : Instrument
    {

        private System.DateTime forwardstartdateField;

        private Basket basketField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime forwardstartdate
        {
            get
            {
                return this.forwardstartdateField;
            }
            set
            {
                this.forwardstartdateField = value;
            }
        }

        /// <remarks/>
        public Basket basket
        {
            get
            {
                return this.basketField;
            }
            set
            {
                this.basketField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.frannuca.org/quantrisk/instrument")]
    public partial class OptionBase : Instrument
    {

        private Amount strikeField;

        private Basket basketField;

        private Barrier[] barrierField;

        private OptionType optionTypeField;

        /// <remarks/>
        public Amount strike
        {
            get
            {
                return this.strikeField;
            }
            set
            {
                this.strikeField = value;
            }
        }

        /// <remarks/>
        public Basket basket
        {
            get
            {
                return this.basketField;
            }
            set
            {
                this.basketField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("barrier")]
        public Barrier[] barrier
        {
            get
            {
                return this.barrierField;
            }
            set
            {
                this.barrierField = value;
            }
        }

        /// <remarks/>
        public OptionType optionType
        {
            get
            {
                return this.optionTypeField;
            }
            set
            {
                this.optionTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.frannuca.org/quantrisk/commons")]
    public partial class Amount
    {

        private double amountField;

        private AmountType amountTypeField;

        /// <remarks/>
        public double amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        /// <remarks/>
        public AmountType amountType
        {
            get
            {
                return this.amountTypeField;
            }
            set
            {
                this.amountTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.frannuca.org/quantrisk/commons")]
    public enum AmountType
    {

        /// <remarks/>
        ABSOLUTE,

        /// <remarks/>
        PERCENTAGE,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.frannuca.org/quantrisk/commons")]
    public partial class Barrier
    {

        private Amount levelField;

        private BarrierType barrierTypeField;

        /// <remarks/>
        public Amount level
        {
            get
            {
                return this.levelField;
            }
            set
            {
                this.levelField = value;
            }
        }

        /// <remarks/>
        public BarrierType barrierType
        {
            get
            {
                return this.barrierTypeField;
            }
            set
            {
                this.barrierTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.frannuca.org/quantrisk/commons")]
    public enum BarrierType
    {

        /// <remarks/>
        UpIn,

        /// <remarks/>
        UpOut,

        /// <remarks/>
        DownIn,

        /// <remarks/>
        DownOut,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.frannuca.org/quantrisk/commons")]
    public enum OptionType
    {

        /// <remarks/>
        CALL,

        /// <remarks/>
        PUT,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.frannuca.org/quantrisk/portfolio")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.frannuca.org/quantrisk/portfolio", IsNullable = false)]
    public partial class Portfolio
    {

        private Instrument[] instrumentsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("instruments")]
        public Instrument[] instruments
        {
            get
            {
                return this.instrumentsField;
            }
            set
            {
                this.instrumentsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class SimulationCube
    {

        private uint number_of_simulationsField;

        private uint number_of_time_stepsField;

        private uint number_of_assetsField;

        private float dtField;

        private CorrelationMatrix assets_correlationField;

        private float dt1Field;

        private uint seedField;

        private uint seed2Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public uint number_of_simulations
        {
            get
            {
                return this.number_of_simulationsField;
            }
            set
            {
                this.number_of_simulationsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public uint number_of_time_steps
        {
            get
            {
                return this.number_of_time_stepsField;
            }
            set
            {
                this.number_of_time_stepsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public uint number_of_assets
        {
            get
            {
                return this.number_of_assetsField;
            }
            set
            {
                this.number_of_assetsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public float dt
        {
            get
            {
                return this.dtField;
            }
            set
            {
                this.dtField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public CorrelationMatrix assets_correlation
        {
            get
            {
                return this.assets_correlationField;
            }
            set
            {
                this.assets_correlationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dt", Order = 5)]
        public float dt1
        {
            get
            {
                return this.dt1Field;
            }
            set
            {
                this.dt1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public uint seed
        {
            get
            {
                return this.seedField;
            }
            set
            {
                this.seedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public uint seed2
        {
            get
            {
                return this.seed2Field;
            }
            set
            {
                this.seed2Field = value;
            }
        }
    }
}
